SOVEREIGN_FUNDS = {
    "norway-gpf": {
        "display_name": "Norway Government Pension Fund",
        "flag": "Norway",
        "country": "Norway",
        "aum_musd": 1570000,
        "top_holdings": [
            {"symbol": "AAPL", "name": "Apple Inc.", "weight": 2.8, "value": 43960, "country": "USA"},
            {"symbol": "MSFT", "name": "Microsoft Corp.", "weight": 2.1, "value": 32970, "country": "USA"},
            {"symbol": "GOOGL", "name": "Alphabet Inc.", "weight": 1.9, "value": 29830, "country": "USA"},
            {"symbol": "NESN.SW", "name": "Nestle SA", "weight": 1.5, "value": 23550, "country": "Switzerland"},
            {"symbol": "ASML", "name": "ASML Holding", "weight": 1.4, "value": 21980, "country": "Netherlands"},
            {"symbol": "7203.T", "name": "Toyota Motor Corp", "weight": 1.3, "value": 20410, "country": "Japan"},
            {"symbol": "VOW3.DE", "name": "Volkswagen AG", "weight": 1.1, "value": 17270, "country": "Germany"},
            {"symbol": "TSLA", "name": "Tesla Inc.", "weight": 1.0, "value": 15700, "country": "USA"},
            {"symbol": "BP.L", "name": "BP plc", "weight": 0.9, "value": 14130, "country": "UK"},
            {"symbol": "META", "name": "Meta Platforms", "weight": 0.8, "value": 12560, "country": "USA"},
            {"symbol": "KCHOL.IS", "name": "Koc Holding", "weight": 0.74, "value": 115.6, "country": "Turkey"},
            {"symbol": "AKBNK.IS", "name": "Akbank", "weight": 0.72, "value": 113.5, "country": "Turkey"},
        ],
    },
    "gic-singapore": {
        "display_name": "GIC Singapore",
        "flag": "Singapore",
        "country": "Singapore",
        "aum_musd": 690000,
        "top_holdings": [
            {"symbol": "MSFT", "name": "Microsoft Corp.", "weight": 3.2, "value": 22080, "country": "USA"},
            {"symbol": "AAPL", "name": "Apple Inc.", "weight": 2.9, "value": 20010, "country": "USA"},
            {"symbol": "AMZN", "name": "Amazon.com Inc.", "weight": 2.1, "value": 14490, "country": "USA"},
            {"symbol": "NVDA", "name": "NVIDIA Corp.", "weight": 1.8, "value": 12420, "country": "USA"},
            {"symbol": "GOOGL", "name": "Alphabet Inc.", "weight": 1.6, "value": 11040, "country": "USA"},
            {"symbol": "SAP", "name": "SAP SE", "weight": 1.4, "value": 9660, "country": "Germany"},
            {"symbol": "HSBC", "name": "HSBC Holdings", "weight": 1.2, "value": 8280, "country": "UK"},
            {"symbol": "6758.T", "name": "Sony Group Corp", "weight": 1.1, "value": 7590, "country": "Japan"},
            {"symbol": "0700.HK", "name": "Tencent Holdings", "weight": 0.55, "value": 3795, "country": "China"},
            {"symbol": "005930.KS", "name": "Samsung Electronics", "weight": 0.48, "value": 3312, "country": "South Korea"},
            {"symbol": "RELIANCE.NS", "name": "Reliance Industries", "weight": 0.42, "value": 2898, "country": "India"},
        ],
    },
    "saudi-pif": {
        "display_name": "Saudi Arabia PIF",
        "flag": "Saudi Arabia",
        "country": "Saudi Arabia",
        "aum_musd": 620000,
        "top_holdings": [
            {"symbol": "UBER", "name": "Uber Technologies", "weight": 5.1, "value": 31620, "country": "USA"},
            {"symbol": "LCID", "name": "Lucid Group Inc.", "weight": 4.8, "value": 29760, "country": "USA"},
            {"symbol": "TSLA", "name": "Tesla Inc.", "weight": 3.2, "value": 19840, "country": "USA"},
            {"symbol": "DIS", "name": "Walt Disney Co.", "weight": 2.1, "value": 13020, "country": "USA"},
            {"symbol": "STLA", "name": "Stellantis NV", "weight": 1.9, "value": 11780, "country": "Netherlands"},
            {"symbol": "EA", "name": "Electronic Arts", "weight": 1.5, "value": 9300, "country": "USA"},
            {"symbol": "VOD.L", "name": "Vodafone Group", "weight": 1.2, "value": 7440, "country": "UK"},
            {"symbol": "BABA", "name": "Alibaba Group", "weight": 1.1, "value": 6820, "country": "China"},
            {"symbol": "9984.T", "name": "SoftBank Group", "weight": 0.9, "value": 5580, "country": "Japan"},
            {"symbol": "BMW.DE", "name": "BMW AG", "weight": 0.85, "value": 5270, "country": "Germany"},
            {"symbol": "005930.KS", "name": "Samsung Electronics", "weight": 0.58, "value": 3596, "country": "South Korea"},
        ],
    },
    "turkey-wealth-fund": {
        "display_name": "Turkey Wealth Fund",
        "flag": "Turkey",
        "country": "Turkey",
        "aum_musd": 45000,
        "top_holdings": [
            {"symbol": "THYAO.IS", "name": "Turkish Airlines", "weight": 8.5, "value": 3825, "country": "Turkey"},
            {"symbol": "TUPRS.IS", "name": "Tupras", "weight": 7.2, "value": 3240, "country": "Turkey"},
            {"symbol": "PETKM.IS", "name": "Petkim", "weight": 6.1, "value": 2745, "country": "Turkey"},
            {"symbol": "TCELL.IS", "name": "Turkcell", "weight": 5.8, "value": 2610, "country": "Turkey"},
            {"symbol": "EREGL.IS", "name": "Eregli Demir Celik", "weight": 4.9, "value": 2205, "country": "Turkey"},
            {"symbol": "AKBNK.IS", "name": "Akbank", "weight": 4.2, "value": 1890, "country": "Turkey"},
            {"symbol": "GARAN.IS", "name": "Garanti BBVA", "weight": 3.8, "value": 1710, "country": "Turkey"},
            {"symbol": "ASELS.IS", "name": "Aselsan", "weight": 3.5, "value": 1575, "country": "Turkey"},
        ],
    },
    "japan-gpif": {
        "display_name": "Japan GPIF",
        "flag": "Japan",
        "country": "Japan",
        "aum_musd": 1650000,
        "top_holdings": [
            {"symbol": "7203.T", "name": "Toyota Motor", "weight": 3.2, "value": 52800, "country": "Japan"},
            {"symbol": "6758.T", "name": "Sony Group", "weight": 2.8, "value": 46200, "country": "Japan"},
            {"symbol": "9984.T", "name": "SoftBank Group", "weight": 2.4, "value": 39600, "country": "Japan"},
            {"symbol": "6861.T", "name": "Keyence Corp", "weight": 2.1, "value": 34650, "country": "Japan"},
            {"symbol": "8306.T", "name": "Mitsubishi UFJ", "weight": 1.9, "value": 31350, "country": "Japan"},
            {"symbol": "AAPL", "name": "Apple Inc.", "weight": 1.7, "value": 28050, "country": "USA"},
            {"symbol": "MSFT", "name": "Microsoft Corp.", "weight": 1.5, "value": 24750, "country": "USA"},
            {"symbol": "GOOGL", "name": "Alphabet Inc.", "weight": 1.2, "value": 19800, "country": "USA"},
            {"symbol": "ASML", "name": "ASML Holding", "weight": 1.1, "value": 18150, "country": "Netherlands"},
            {"symbol": "NESN.SW", "name": "Nestle SA", "weight": 0.95, "value": 15675, "country": "Switzerland"},
        ],
    },
    "germany-pension-fund": {
        "display_name": "Germany Pension Fund",
        "flag": "Germany",
        "country": "Germany",
        "aum_musd": 280000,
        "top_holdings": [
            {"symbol": "SAP", "name": "SAP SE", "weight": 4.2, "value": 11760, "country": "Germany"},
            {"symbol": "SIE.DE", "name": "Siemens AG", "weight": 3.8, "value": 10640, "country": "Germany"},
            {"symbol": "VOW3.DE", "name": "Volkswagen AG", "weight": 3.5, "value": 9800, "country": "Germany"},
            {"symbol": "ALV.DE", "name": "Allianz SE", "weight": 3.2, "value": 8960, "country": "Germany"},
            {"symbol": "ASML", "name": "ASML Holding", "weight": 2.9, "value": 8120, "country": "Netherlands"},
            {"symbol": "AAPL", "name": "Apple Inc.", "weight": 2.5, "value": 7000, "country": "USA"},
            {"symbol": "MSFT", "name": "Microsoft Corp.", "weight": 2.2, "value": 6160, "country": "USA"},
            {"symbol": "BAS.DE", "name": "BASF SE", "weight": 2.0, "value": 5600, "country": "Germany"},
            {"symbol": "NESN.SW", "name": "Nestle SA", "weight": 1.8, "value": 5040, "country": "Switzerland"},
            {"symbol": "MC.PA", "name": "LVMH", "weight": 1.6, "value": 4480, "country": "France"},
        ],
    },
    "uk-ppf": {
        "display_name": "UK Pension Protection Fund",
        "flag": "United Kingdom",
        "country": "United Kingdom",
        "aum_musd": 420000,
        "top_holdings": [
            {"symbol": "HSBC", "name": "HSBC Holdings", "weight": 3.8, "value": 15960, "country": "UK"},
            {"symbol": "BP.L", "name": "BP plc", "weight": 3.5, "value": 14700, "country": "UK"},
            {"symbol": "SHEL.L", "name": "Shell plc", "weight": 3.2, "value": 13440, "country": "UK"},
            {"symbol": "AZN.L", "name": "AstraZeneca", "weight": 2.9, "value": 12180, "country": "UK"},
            {"symbol": "ULVR.L", "name": "Unilever", "weight": 2.6, "value": 10920, "country": "UK"},
            {"symbol": "RIO.L", "name": "Rio Tinto", "weight": 2.3, "value": 9660, "country": "UK"},
            {"symbol": "AAPL", "name": "Apple Inc.", "weight": 2.0, "value": 8400, "country": "USA"},
            {"symbol": "MSFT", "name": "Microsoft Corp.", "weight": 1.8, "value": 7560, "country": "USA"},
            {"symbol": "ASML", "name": "ASML Holding", "weight": 1.65, "value": 6930, "country": "Netherlands"},
            {"symbol": "NESN.SW", "name": "Nestle SA", "weight": 1.52, "value": 6384, "country": "Switzerland"},
        ],
    },
}
